import type { NextPage } from 'next'
import Head from 'next/head'
import { AnimatePresence } from 'framer-motion'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>My-Dashboard</title>
				<meta
					name='An alternative to browser startup pages.'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/icon.svg' />
			</Head>

			<AnimatePresence exitBeforeEnter>
				<h2 className='bg-blue-dark font-poppins text-teal-light text-center text-5xl'>
					Hello World
				</h2>
			</AnimatePresence>
		</div>
	)
}

export default Home
